### ISSUE TITLE
It's very good!

### ISSUE THREAD

**Issue by KisSzoke** [G6EJD/ESP-Web-Server-v2#2]
Hi!
It's fantastic and I also do it, but I have a problem.
I want to control an RGB LED strip too. Can be possible? But I can't get the value of RGB. Do you have any idea?
It will be fantastic, if you can help me. 
Sincerely
KisSzoke!

**Comment by G6EJD** [comment]
OK, what LED (RGB) type are you using?
Most are controlled by three parameters like 100,200,300 for RGB, I think all you need to do it get a parameter as an input and type is '100,200,300' then you'd have a value that you could interpret and parse to the RGB LED.
So you get an input like:
100,200,300
Which will be text, then:
int R,G,B;
R = parameter_name.substring(0,3).toInt();
G = parameter_name.substring(4,7).toInt();
B = parameter_name.substring(8,11).toInt();

Then 
RGB_Control(R,G,B);

**Comment by KisSzoke** [comment]
RGB type is not important. I want to control it with PWM 
I want to send data (for example 3 number) to ESP8266 from sdwebserver.
Could i send data from the webpage? Maybe i can use Input field or a slider. 
If i can send from webpage, how can i get it on the esp8266.
So data from html to arduino(ESP)

**Comment by G6EJD** [comment]
have a look at (if not already) https://github.com/G6EJD/ESP8266-Configurable-Webserver-Template/blob/master/ESP8266_GP_Webserver_01.ino

What you need to do is get an input from a client and then apply that input to your LED as a PWM value.

Getting the data in is relatively easy. HTRML code is generated by the ESP8266 and so is input read, so your ESP has access to the user input data, once converted to an integer or whatever to make is usable.

In it's simplest form you'd connect to the server with a command like this:

http://192.168.0.50/Level-1

And at in the server code (around Line-73 in my source-code) add new response commands:
server.on("/Level-1",  Set_led_10); 
server.on("/Level-2",  Set_led_20);
... 
server.on("/Level-8",  Set_led_80); 
server.on("/Level-9",  Set_led_90); 

then add a function for each response:

void Set_led_10(){
   append_webpage_header(); 
   webpage += "<div id=\"header\"><h1>ESP8266 DHT11 Web Server LED Control</h1></div>"; 
   webpage += "<div id=\"section\"><h2>LED Status</h2>"; 
   webpage += "LED has been set to 10%"; 
   webpage += "</div>"; 
   webpage += "<p><a href=\"page3.htm\">LED Controls</a></p>"; 
   webpage += "<div id=\"footer\">Copyright &copy; D L Bird 2016</div>"; 
   webpage += "<p><a href=\"index.htm\">Home Page</a></p></body></html>"; 
   server.send(200, "text/html", webpage); 
   pinMode(LED_BUILTIN, OUTPUT);     // Initialize the LED_BUILTIN pin as an output 
  analogWrite(ledPin, (10/100*255));   // 0 = OFF 255 =Full On 
   delay(1000); 
   Serial.println("LED set to 10%"); 
} 
...
void Set_led_90(){
   append_webpage_header(); 
   webpage += "<div id=\"header\"><h1>ESP8266 DHT11 Web Server LED Control</h1></div>"; 
   webpage += "<div id=\"section\"><h2>LED Status</h2>"; 
   webpage += "LED has been set to 90%"; 
   webpage += "</div>"; 
   webpage += "<p><a href=\"page3.htm\">LED Controls</a></p>"; 
   webpage += "<div id=\"footer\">Copyright &copy; D L Bird 2016</div>"; 
   webpage += "<p><a href=\"index.htm\">Home Page</a></p></body></html>"; 
   server.send(200, "text/html", webpage); 
   pinMode(LED_BUILTIN, OUTPUT);     // Initialize the LED_BUILTIN pin as an output 
  analogWrite(ledPin, (90/100*255));    // 0 = OFF 255 =Full On 
   delay(1000); 
   Serial.println("LED set to 90%"); 
} 

The next stage would be to add a page that gets an input and then sends that to the server for action.

What I've described will get you going though.

**Comment by G6EJD** [comment]
Github cannot handle pasting literals, but I'm sure you get the gist.

**Comment by KisSzoke** [comment]
OK.
Thank you very much! 👍 :) :1st_place_medal:

**Comment by G6EJD** [comment]
I've just uploaded an example for you, just needs some tidying up, spaces between commands, does not need to use the SD-Card either. A proof of principle for you. LED can be controlled in 10% increments.

When I have controlled an LED, I have found the response to be non-linear, so don't expect much difference between 10 and 20% PWM values.

**Comment by G6EJD** [comment]
A lot of the code in the example is now unused, so could be considerably shorter.
